# Generated by Django 4.2.30 on 2026-04-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=18, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('employment_status', models.CharField(choices=[('在职', '在职'), ('停用', '停用'), ('离职', '离职')], default='在职', max_length=20)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', '信息'), ('warning', '预警'), ('success', '成功'), ('error', '异常')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_type', models.CharField(choices=[('全部', '全部'), ('特种作业', '特种作业'), ('特种设备', '特种设备')], default='全部', max_length=20)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已完成', '已完成'), ('无记录', '无记录'), ('失败', '失败'), ('已取消', '已取消')], default='待处理', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('new_cert_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enqueued_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_tasks', to='certs.employee')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_source', models.CharField(blank=True, default='manual', max_length=50)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('diff_summary', models.JSONField(blank=True, default=dict)),
                ('has_new_data', models.BooleanField(default=False)),
                ('status', models.CharField(default='成功', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='certs.querytask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.CharField(max_length=100)),
                ('operation_item', models.CharField(blank=True, default='', max_length=100)),
                ('cert_number', models.CharField(blank=True, default='', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('actual_review_date', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('manual', '手工录入'), ('import', '外部导入')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('有效', '有效'), ('已过期', '已过期'), ('待复审', '待复审'), ('作废', '作废')], default='有效', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certs.employee')),
            ],
            options={
                'ordering': ['employee__name', 'certificate_type', '-expiry_date', '-id'],
            },
        ),
    ]
