flowchart TD
  A["dwd_mes_mm_task_group_output"] --> B["ads_sc_xl_13_process1"]
  B --> C["ads_sc_xl_13_defined"]
  C --> D["ads_sc_xl_13_defined_manuf_line_name"]
  D --> E["ads_sc_xl_13_defined_manuf_line_name_combined"]
  E --> F["combined_001"]
  E --> G["combined_002"]
