flowchart TD
  "hmes_prd.mm_task_group_output" --> "ods_mes_mm_task_group_output"
  "hmes_prd.mm_task_prod_actual" --> "ods_mes_mm_task_prod_actual"
  "hmes_prd.wms_wh_enter" --> "ods_mes_wms_wh_enter"
  "hmes_prd.wms_wh_enter_item" --> "ods_mes_wms_wh_enter_item"
  "hmes_prd.wms_batch_info" --> "ods_mes_wms_batch_info"
  "ods_mes_mm_task_group_output" --> "dwd_mes_mm_task_group_output"
  "ods_mes_mm_task_prod_actual" --> "dwd_mes_mm_task_group_output"
  "with_attr_value" --> "dwd_mes_mm_task_group_output"
  "dwd_silicon_steel_surface_info" --> "dwd_mes_mm_task_group_output"
  "ods_mes_mm_task_prod_actual" --> "dwd_task_prod_actual"
  "ods_mes_wms_batch_info" --> "dwd_task_prod_actual"
  "ods_mes_wms_wh_enter_item" --> "dwd_mes_wms_wh_enter_item"
  "ods_mes_wms_wh_enter" --> "dwd_mes_wms_wh_enter_item"
  "ods_mes_wms_batch_info" --> "dwd_mes_wms_wh_enter_item"
  "dim_ums_tenant" --> "dwd_mes_wms_wh_enter_item"
  "dwd_mes_wms_wh_enter_item" --> "ads_sc_xl_01"
  "dwd_mes_mm_task_group_output" --> "ads_sc_xl_13_process1"
  "ads_sc_xl_13_process1" --> "ads_sc_xl_13_defined"
  "dim_date_info" --> "ads_sc_xl_13_defined"
  "ads_sc_xl_13_defined" --> "ads_sc_xl_13_defined_manuf_line_name"
  "ads_sc_xl_13_defined_manuf_line_name" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "with_attr_value" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "with_result_confirm" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_01" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_13_defined_manuf_line_name_combined_process1" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_13_defined_manuf_line_name_avg_thickness_data" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_13_defined_manuf_line_name_finished_output_tons_lz" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_13_defined_manuf_line_name_finished_product_lz" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "attr1='合计'" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "manuf_line_name='总计'" --> "ads_sc_xl_13_defined_manuf_line_name_combined"
  "ads_sc_xl_13_defined_manuf_line_name_combined" --> "ads_sc_xl_13_defined_manuf_line_name_combined_001"
  "ads_sc_xl_13_defined_manuf_line_name_combined" --> "ads_sc_xl_13_defined_manuf_line_name_combined_002"
  "UNKNOWN_tenant_transform" --> "ods_mes_mdm_tenant"
  "UNKNOWN_tenant_transform" --> "dim_ums_tenant"
